### ISSUE TITLE
eventlistener not running

### ISSUE THREAD

**Issue by kra** [kra/futel-installation#192]
can't connect to asterisk, being killed by supervisor
maybe because supervisor is trying to start it before asterisk is running?
solution could be to run asterisk in supervisor instead of as a service
or, config supervisor to try harder, back off slower so it is still trying to start eventlistener by the time asterisk is up? Hackish.

**Comment by kra** [comment]
Traceback (most recent call last):
  File "/opt/futel/src/eventlistener.py", line 95, in <module>
    main()
  File "/opt/futel/src/eventlistener.py", line 69, in main
    amanager = get_manager()
  File "/opt/futel/src/eventlistener.py", line 54, in get_manager
    amanager.connect(asterisk_ip)
  File "/usr/lib/python2.7/site-packages/asterisk/manager.py", line 449, in connect
    raise ManagerSocketException(errno, reason)
asterisk.manager.ManagerSocketException: (111, 'Connection refused')

**Comment by kra** [comment]
on vm this failed until I turned off iptables
